apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-testing-externalname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      environment: testing-externalname
  template:
    metadata:
      labels:
        app: nginx
        environment: testing-externalname
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80