apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    project: nginx
    environment: testing
    
spec:
  containers:
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 80