apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm-file
spec:
  volumes:
    - name: config-volume
      configMap: 
        name: nginx-config-dir

  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
      - name: config-volume
        mountPath: /etc/nginx/conf.d/
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
